insert into public.originals
  (id, slug, name, brand, category, price_gbp, blurb, description,
   auto_image_url, image_credit, tags, artists, aliases, popularity, search_query)
values
('org-oc-2','boss-oc-2-oc-3-octave','Boss OC-2 / OC-3 Octave','Boss','octave',129,'Analogue sub-octaves that turn a guitar into a synth bass.','The OC-2 tracks one and two octaves below whatever you play and blends them against your dry signal. It''s monophonic and famously fussy — play a chord and it panics — but on single notes above the fifth fret it produces a thick, rubbery synth bass that nothing else quite matches. That flaw became the sound: the tracking glitches are a large part of why producers still reach for it. The OC-3 adds a polyphonic mode and a drive setting.','https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Boss_OC-3_Super_Octave.jpg/960px-Boss_OC-3_Super_Octave.jpg','wikimedia — CC BY-SA 4.0',ARRAY['oc-2','oc2','oc-3','oc3','octave','octaver','boss','sub octave','bass','synth','pitch']::text[],ARRAY['Jack White','Josh Homme','Tom Morello','Matt Bellamy']::text[],'{}',82,'Boss OC-3 Super Octave'),
('org-vb-2','boss-vb-2-vibrato','Boss VB-2 Vibrato','Boss','modulation',199,'True pitch vibrato — the seasick wobble a chorus can''t do.','Genuine vibrato bends pitch up and down with no dry signal mixed in, which is a very different thing from the chorus most pedals actually give you. The VB-2 was made for only four years in the 80s, and its Rise Time control — which eases the effect in gradually after you engage it — is the feature that made it a cult item. Originals are scarce and expensive; the VB-2W Waza reissue brought the circuit back.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/379482.jpg','thomann',ARRAY['vb-2','vb2','vibrato','boss','modulation','pitch','seasick','vb-2w','waza']::text[],ARRAY['John Frusciante','Kevin Shields','Radiohead']::text[],'{}',66,'Boss VB-2W Vibrato'),
('org-plexitone','carl-martin-plexitone','Carl Martin Plexitone','Carl Martin','distortion',199,'A cranked Marshall Plexi in a box, running on real 12V internally.','Most amp-in-a-box pedals approximate the idea; the Plexitone runs an internal 12V power supply to give its circuit genuine headroom, which is why it stays tight and amp-like where cheaper Plexi pedals get fizzy. Two footswitchable gain levels cover crunch rhythm and full lead. It''s aimed squarely at the late-60s Marshall sound — midrange bite, sag under a hard pick attack, and cleanup from the guitar''s volume knob.','https://m.media-amazon.com/images/I/81jGK9SiylL._AC_SL600_.jpg','amazon',ARRAY['plexitone','carl martin','plexi','marshall','amp in a box','distortion','crunch','british']::text[],ARRAY['Andy Timmons','Robben Ford']::text[],'{}',64,'Carl Martin Plexitone'),
('org-tremulator','demeter-tremulator','Demeter Tremulator','Demeter','modulation',169,'The opto tremolo everything else gets compared to.','An optical tremolo built around a light-dependent resistor, which gives it a soft, rounded pulse rather than the hard chop of a digital tremolo. Two knobs — speed and depth — and a sound that flatters clean amps immediately. It has been in production since the 1980s and is the reference point for the effect; when a review says a tremolo sounds ''organic'', this is usually the thing it''s being measured against.',NULL,NULL,ARRAY['tremulator','demeter','carl martin','tremolo','trem','opto','optical','modulation','surf']::text[],ARRAY['Bill Frisell','Daniel Lanois','Jonny Greenwood']::text[],'{}',61,'Demeter Tremulator'),
('org-boneshaker','dod-boneshaker','DOD Boneshaker','DOD','distortion',129,'High-gain distortion with a three-band parametric EQ bolted on.','Designed with Jamie Stillman of EarthQuaker Devices, the Boneshaker pairs an aggressive high-gain distortion with a genuinely powerful three-band EQ — including a sweepable midrange — so you can carve it into almost anything from scooped modern metal to a honking midrange lead. That much control is unusual at any price, and it makes the pedal far more flexible than the average distortion box.','https://m.media-amazon.com/images/I/61cnRDw7CRL._AC_SL600_.jpg','amazon',ARRAY['boneshaker','dod','distortion','high gain','parametric','earthquaker','stillman','metal']::text[],ARRAY['Jamie Stillman']::text[],'{}',58,'DOD Boneshaker Distortion'),
('org-carcosa','dod-carcosa-fuzz','DOD Carcosa Fuzz','DOD','fuzz',119,'Gated, spitty fuzz with two very different voices.','Named after the lost city in Robert W. Chambers'' fiction, the Carcosa is a modern take on the gated fuzz — the sort that splutters and cuts out as notes decay. A Hali/Demhe voicing switch flips between a scooped, aggressive tone and a thicker midrange one, and the Bias control lets you starve the circuit for the classic dying-battery sound. It is far more controllable than most gated fuzzes, which usually give you one setting that works.','https://m.media-amazon.com/images/I/61xMP39K0zL._AC_SL600_.jpg','amazon',ARRAY['carcosa','dod','fuzz','gated fuzz','bias','velcro','spitty','hali','demhe']::text[],ARRAY['Jamie Stillman']::text[],'{}',52,'DOD Carcosa Fuzz'),
('org-fuzz-face','dunlop-fuzz-face','Dunlop / Dallas Arbiter Fuzz Face','Dunlop','fuzz',129,'Two transistors, two knobs, and the most famous fuzz ever built.','The circuit Hendrix made immortal: a two-transistor design in a round enclosure that looks like a smiling face. Germanium versions are warm and temperamental — they drift with temperature and clean up beautifully from the guitar''s volume knob — while silicon versions are brighter and more consistent. It is famously fussy about what sits in front of it, which is why players put it first in the chain, straight after the guitar.',NULL,NULL,ARRAY['fuzz face','dunlop','dallas arbiter','hendrix','germanium','silicon','fuzz','ffm','jhf1']::text[],ARRAY['Jimi Hendrix','David Gilmour','Eric Johnson','Stevie Ray Vaughan']::text[],'{}',90,'Dunlop Fuzz Face Mini'),
('org-big-muff','electro-harmonix-big-muff-pi','Electro-Harmonix Big Muff Pi','Electro-Harmonix','fuzz',89,'Endless sustain and a scooped wall of fuzz.','Four transistors, two clipping stages and a midrange scoop so deep it can vanish in a band mix — which is exactly why it sounds enormous on its own. The Big Muff is really a sustain machine: notes bloom and hold rather than decay. It has been made in dozens of variants since 1969, and the differences between them are the entire reason a clone market exists. The standard NYC version is the cheapest way in.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/212802.jpg','thomann',ARRAY['big muff','muff','electro-harmonix','ehx','fuzz','sustain','pi','smashing pumpkins','gilmour','nyc']::text[],ARRAY['David Gilmour','Billy Corgan','Jack White','J Mascis','Dinosaur Jr']::text[],'{}',95,'Electro-Harmonix Big Muff Pi'),
('org-black-russian','electro-harmonix-black-russian-big-muff','Electro-Harmonix Black Russian Big Muff','Electro-Harmonix','fuzz',179,'The darkest, heaviest Muff — a doom and stoner staple.','Built in the Sovtek factory in Russia through the late 90s in a heavy black box, this version is darker and more compressed than the NYC Big Muff, with a thicker low end and less top-end fizz. That combination made it the fuzz of choice for doom, sludge and stoner rock. Prices have climbed steadily as supply dried up, and it is now one of the most sought-after Muff variants.',NULL,NULL,ARRAY['black russian','big muff','sovtek','electro-harmonix','ehx','fuzz','doom','sludge','stoner','dark']::text[],ARRAY['Matt Pike','Electric Wizard','Dan Auerbach']::text[],'{}',78,'Electro-Harmonix Black Russian Big Muff'),
('org-green-russian','electro-harmonix-green-russian-big-muff','Electro-Harmonix Green Russian Big Muff','Electro-Harmonix','fuzz',99,'Thick, tight low end with less scoop than a standard Muff.','The mid-90s Sovtek Muff in a green enclosure, reissued by Electro-Harmonix at a sensible price. Compared to the NYC version it has a tighter, punchier bottom end and a less severe midrange scoop, which means it sits in a mix far better — a common complaint about standard Big Muffs is that they disappear behind a band. That makes this the practical choice of the Muff family.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/420472.jpg','thomann',ARRAY['green russian','big muff','sovtek','electro-harmonix','ehx','fuzz','civil war','tight','reissue']::text[],ARRAY['Matt Pike','Josh Homme','Kurt Ballou']::text[],'{}',81,'Electro-Harmonix Green Russian Big Muff')
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  price_gbp = excluded.price_gbp,
  blurb = excluded.blurb,
  description = excluded.description,
  auto_image_url = excluded.auto_image_url,
  image_credit = excluded.image_credit,
  tags = excluded.tags,
  artists = excluded.artists,
  aliases = excluded.aliases,
  popularity = excluded.popularity,
  search_query = excluded.search_query;
