insert into public.originals
  (id, slug, name, brand, category, price_gbp, blurb, description,
   auto_image_url, image_credit, tags, artists, aliases, popularity, search_query)
values
('org-tube-screamer','ibanez-tube-screamer','Ibanez Tube Screamer (TS9 / TS808)','Ibanez','overdrive',179,'The mid-humped overdrive that defined blues and rock lead tone.','Arguably the most cloned circuit in guitar history. The Tube Screamer''s trick is a pronounced midrange bump and a soft, symmetrical clipping stage that pushes a valve amp into breakup without swamping it. Stack it in front of a cranked amp and it tightens the low end and shoves the mids forward — which is why it has sat on pedalboards from Stevie Ray Vaughan to modern metal rigs. The TS808 is the warmer, lower-output original; the TS9 is slightly brighter and more aggressive.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/104010.jpg','thomann',ARRAY['tube screamer','ts9','ts808','ts-9','overdrive','od','srv','stevie ray vaughan','green','mid hump','boost']::text[],ARRAY['Stevie Ray Vaughan','John Mayer','Kirk Hammett','The Edge','Gary Moore']::text[],'{}',98,'Ibanez TS9 Tube Screamer'),
('org-bd-2','boss-bd-2-blues-driver','Boss BD-2 Blues Driver','Boss','overdrive',109,'Glassy, amp-like overdrive that cleans right up with your volume knob.','Where the Tube Screamer scoops nothing and pushes mids, the BD-2 goes the other way — open, bright and startlingly touch-sensitive. Roll your guitar volume back and it cleans up almost completely; dig in and it snarls. That dynamic response is why it has outlived most of Boss''s overdrive line and why the Keeley-modded version became a cottage industry of its own. Its one weakness is a slightly thin low end and a fizz that creeps in at maximum gain.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/103955.jpg','thomann',ARRAY['bd-2','bd2','blues driver','boss','overdrive','transparent','amp-like','keeley','dynamic']::text[],ARRAY['John Mayer','Prince','Jack White','Robben Ford']::text[],'{}',92,'Boss BD-2 Blues Driver'),
('org-bf-2','boss-bf-2-flanger','Boss BF-2 Flanger','Boss','modulation',179,'All-analogue BBD flanger behind countless 80s jet-sweeps.','A bucket-brigade flanger built between 1980 and 2001, and long discontinued — which is why clean examples now cost more than most new pedals. The BF-2 does everything from a subtle rotary-ish shimmer through to full jet-plane whoosh, and its Resonance control will take off into metallic self-oscillation if you push it. Analogue BBD chips give it a warmth and a slight high-end roll-off that digital flangers spend a lot of effort trying to model.',NULL,NULL,ARRAY['bf-2','bf2','flanger','boss','analog flanger','analogue','jet','modulation','bbd']::text[],ARRAY['Andy Summers','The Edge','Kurt Cobain','Alex Lifeson']::text[],'{}',74,'Boss BF-2 Flanger'),
('org-ce-2','boss-ce-2-chorus','Boss CE-2 Chorus','Boss','modulation',229,'The warm two-knob analogue chorus that defined 80s clean tone.','Two knobs, no menus, and a sound that put a shimmer on half the records made in the 1980s. The CE-2 is a single-voice analogue BBD chorus — thicker and less watery than the stereo CE-1 that preceded it — and it flatters clean amps in a way that is hard to argue with. Original units have climbed steeply on the used market, and the Waza Craft CE-2W reissue is not cheap either, which makes this one of the most worthwhile clones to chase.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/393030.jpg','thomann',ARRAY['ce-2','ce2','chorus','boss','analog chorus','analogue','modulation','80s','bbd','ce-2w']::text[],ARRAY['Andy Summers','Johnny Marr','Kurt Cobain','Peter Buck']::text[],'{}',88,'Boss CE-2 Chorus'),
('org-dd-2','boss-dd-2-dd-3-digital-delay','Boss DD-2 / DD-3 Digital Delay','Boss','delay',139,'The industry-standard digital delay — clean repeats and a killer hold function.','The DD-2 was the first compact digital delay pedal, and the DD-3 is essentially the same circuit sold at a sane price for three decades. Repeats are clean and uncoloured rather than dark and analogue, which makes it the sensible choice when you want the delay to sit behind the note instead of smearing it. The Hold function — infinite repeat at the stomp of the switch — is still the most fun feature Boss ever shipped, and the reason DD-2s hold their value.','https://m.media-amazon.com/images/I/61y5oAYxizL._AC_SL600_.jpg','amazon',ARRAY['dd-2','dd2','dd-3','dd3','delay','boss','digital delay','echo','repeats','hold']::text[],ARRAY['The Edge','Kevin Shields','Johnny Marr','Nels Cline']::text[],'{}',90,'Boss DD-3 Digital Delay'),
('org-dm-2','boss-dm-2-dm-3-analog-delay','Boss DM-2 / DM-3 Analog Delay','Boss','delay',199,'Dark, warm bucket-brigade echoes that sit behind the note instead of on top of it.','The delay people mean when they say they want ''analogue warmth''. Each repeat of a DM-2 is darker and softer than the one before, so the echoes decay into the background rather than competing with what you''re playing. That high-end roll-off is a limitation of bucket-brigade chips, and it turned out to be the single most desirable thing about them. Maximum delay time is short — around 300ms — so this is a slapback and rockabilly machine, not a soundscape pedal.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/345724.jpg','thomann',ARRAY['dm-2','dm2','dm-3','dm3','analog delay','analogue delay','boss','bbd','slapback','echo','warm']::text[],ARRAY['Johnny Marr','J Mascis','Kevin Shields','Robert Smith']::text[],'{}',84,'Boss DM-2W Analog Delay'),
('org-ds-1','boss-ds-1-distortion','Boss DS-1 Distortion','Boss','distortion',55,'The orange box that put distortion on a million pedalboards.','In production almost continuously since 1978 and still one of the cheapest pedals Boss makes, which makes it an unusual entry here — the original is already budget-priced. It''s a hard-clipping distortion with a pronounced midrange scoop and a famously aggressive Tone control, used by everyone from Kurt Cobain to Joe Satriani. Because the DS-1 is so cheap already, the clones below compete on size, build and voicing rather than on price alone.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/102371.jpg','thomann',ARRAY['ds-1','ds1','distortion','boss','orange','nirvana','cobain','satriani']::text[],ARRAY['Kurt Cobain','Joe Satriani','Steve Vai','Prince']::text[],'{}',94,'Boss DS-1 Distortion'),
('org-ge-7','boss-ge-7-graphic-equalizer','Boss GE-7 Graphic Equalizer','Boss','eq',109,'Seven bands of EQ — the most useful unglamorous pedal you can own.','Nobody''s first pedal, and often their most-used. Seven sliders plus a level control let you fix a boxy amp, tame an ice-picky bridge pickup, or kick in a mid-boost for solos. Put it in front of the amp to reshape what your drive pedals see; put it in the loop to reshape the amp itself. The only real complaint about the Boss unit is a slightly noisy op-amp stage, which is why modded versions are a cottage industry.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/103963.jpg','thomann',ARRAY['ge-7','ge7','eq-7','eq7','equalizer','equaliser','graphic eq','boss','eq','mid boost']::text[],ARRAY['John Petrucci','Adam Jones','Mark Tremonti']::text[],'{}',80,'Boss GE-7 Equalizer'),
('org-fz-2','boss-fz-2-hyper-fuzz','Boss FZ-2 Hyper Fuzz','Boss','fuzz',149,'Boss''s take on the Univox Super-Fuzz — vicious, octave-tinged and long discontinued.','Built for only four years in the early 90s and quietly worshipped ever since, largely because of its role in stoner and doom rock. The FZ-2 is essentially a Univox Super-Fuzz with a two-band EQ bolted on and a Gain 1 / Gain 2 mode switch. Gain 2 is where it earns its name: a saturated, octave-up-flavoured roar with a distinctive midrange honk. Original units are scarce and priced accordingly.','https://upload.wikimedia.org/wikipedia/commons/7/76/Boss_Hyper_Fuzz_FZ-2_-_front_angled.jpg','wikimedia — CC BY 2.0',ARRAY['fz-2','fz2','hyper fuzz','boss','fuzz','super fuzz','univox','doom','stoner','octave fuzz']::text[],ARRAY['Matt Pike','Josh Homme','Kevin Shields']::text[],'{}',68,'Boss FZ-2 Hyper Fuzz'),
('org-hm-2','boss-hm-2-heavy-metal','Boss HM-2 Heavy Metal','Boss','distortion',149,'The chainsaw. Every knob fully clockwise, and you have Swedish death metal.','Discontinued in 1991 and largely ignored until Swedish death metal bands discovered that running every control fully clockwise produced a buzzsaw tone nothing else could make. That ''HM-2 all knobs right'' setting is now a genre signature. It''s a distortion with a two-band Colour EQ that is far more extreme than its knob count suggests — the low band adds a chest-thumping fizz, the high band a razor edge. Vintage units command silly prices; the Waza reissue brought it back.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/522244.jpg','thomann',ARRAY['hm-2','hm2','heavy metal','boss','distortion','chainsaw','buzzsaw','swedish death metal','entombed','hm-2w']::text[],ARRAY['Entombed','Nicke Andersson','Dismember','Kurt Ballou']::text[],'{}',89,'Boss HM-2W Heavy Metal')
on conflict (id) do update set
  slug = excluded.slug,
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  price_gbp = excluded.price_gbp,
  blurb = excluded.blurb,
  description = excluded.description,
  auto_image_url = excluded.auto_image_url,
  image_credit = excluded.image_credit,
  tags = excluded.tags,
  artists = excluded.artists,
  aliases = excluded.aliases,
  popularity = excluded.popularity,
  search_query = excluded.search_query;
