insert into public.alternatives
  (id, slug, original_id, name, brand, price_gbp, blurb,
   auto_image_url, image_credit, pros, cons, aliases, popularity,
   match_quality, search_query, verdict, gallery)
values
('alt-angel-wing','tone-city-angel-wing','org-ce-2','Tone City Angel Wing','Tone City',39,'Micro analogue chorus with a genuinely lush top end.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/536647.jpg','thomann',ARRAY['Analogue circuit in a tiny, well-built metal enclosure','Lush and three-dimensional at low Depth settings','True bypass']::text[],ARRAY['No battery option','Micro knobs are fiddly','Less thick than a CE-2 when you push Depth hard']::text[],'{}',58,82,NULL,NULL,ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/536647.jpg','https://m.media-amazon.com/images/I/511xxRA48aL._AC_SL600_.jpg']::text[]),
('alt-jf08','joyo-jf-08-digital-delay','org-dd-2','Joyo JF-08 Digital Delay','Joyo',29,'Clean digital repeats in a metal box for under thirty quid.','https://m.media-amazon.com/images/I/61yFZcAMHrL._AC_SL600_.jpg','amazon',ARRAY['Clean, uncoloured repeats much like the DD-3','Metal enclosure and true bypass','Up to 600ms of delay time — plenty for most songs']::text[],ARRAY['Shorter maximum delay time than the DD-3''s 800ms','No Hold / infinite repeat function','Repeat trails cut off abruptly when you bypass it']::text[],'{}',74,85,NULL,NULL,'{}'),
('alt-reecho','mooer-reecho','org-dd-2','Mooer Reecho','Mooer',45,'Three delay modes in a micro enclosure — more range than the DD-3.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/309291.jpg','thomann',ARRAY['Three modes (analogue, real echo, tape) versus the DD-3''s single digital voice','Micro size saves half the board space of a compact Boss pedal','True bypass and solid metal build']::text[],ARRAY['No battery option','No tap tempo','Fiddly micro knobs for setting precise delay times']::text[],'{}',82,83,NULL,NULL,ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/309291.jpg','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/355109.jpg','https://m.media-amazon.com/images/I/61xdh1xyRsL._AC_SL600_.jpg','https://m.media-amazon.com/images/I/51wZTHz+HeL._AC_SL600_.jpg']::text[]),
('alt-cp17','caline-cp-17','org-dd-2','Caline CP-17','Caline',35,'Warm, slightly darker repeats with a proper metal chassis.','https://m.media-amazon.com/images/I/61SQaAq7J1L._AC_SL600_.jpg','amazon',ARRAY['Aluminium alloy housing that feels well above its price','Warmer, darker repeats that sit behind the guitar nicely','True bypass']::text[],ARRAY['Repeats are less pristine than the DD-3''s','Build consistency varies unit to unit','No Hold function']::text[],ARRAY['Caline CP-17 Delay']::text[],52,80,NULL,NULL,ARRAY['https://m.media-amazon.com/images/I/61SQaAq7J1L._AC_SL600_.jpg']::text[]),
('alt-dd400','behringer-dd400-digital-delay','org-dd-2','Behringer DD400 Digital Delay','Behringer',30,'A DD-3 copy with a longer delay time and a tenth of the price tag.',NULL,NULL,ARRAY['Offers longer maximum delay time than the DD-3 it copies','Includes a Hold-style infinite repeat function','Same control layout, so DD-3 settings transfer directly']::text[],ARRAY['Plastic enclosure and footswitch','Buffered bypass','Slight noise on the repeat tails']::text[],ARRAY['Behringer DD400']::text[],66,88,NULL,NULL,'{}'),
('alt-ad6','eno-ad6-delay','org-dm-2','ENO AD6 Delay','ENO',35,'Genuine BBD analogue delay for the price of a cable.',NULL,NULL,ARRAY['Real bucket-brigade circuit, not a digital emulation of one','Repeats darken and decay much like a DM-2''s','Metal enclosure with true bypass']::text[],ARRAY['Shorter maximum delay time than the original','No UK support or warranty','Some hiss on the repeat tails']::text[],'{}',44,85,NULL,NULL,'{}'),
('alt-ad10','biyang-ad10-delay','org-dm-2','Biyang AD10 Delay','Biyang',49,'Analogue delay with more delay time than the DM-2 ever offered.',NULL,NULL,ARRAY['Longer maximum delay time than the original''s roughly 300ms','True analogue BBD signal path','Heavy metal chassis and true bypass']::text[],ARRAY['Considerably bigger than a compact Boss box','Heavier than everything else on this list','Patchy distribution']::text[],ARRAY['Biyang AD-10']::text[],48,86,NULL,NULL,'{}'),
('alt-anaecho','mooer-anaecho','org-dm-2','Mooer AnaEcho','Mooer',45,'True analogue delay shrunk into a micro enclosure.',NULL,NULL,ARRAY['Genuine BBD analogue delay in a pedal the size of a matchbox','Frees up roughly half the board space of a DM-2','Warm, dark repeats that sit properly behind the guitar']::text[],ARRAY['No battery option','Maximum delay time is short even by DM-2 standards','Micro knobs make precise timing awkward']::text[],ARRAY['Mooer Ana Echo']::text[],79,88,NULL,NULL,ARRAY['https://m.media-amazon.com/images/I/51wZTHz+HeL._AC_SL600_.jpg']::text[]),
('alt-e20dl','daphon-e20dl','org-dm-2','Daphon E20DL','Daphon',18,'Cheapest possible route to a slapback echo.',NULL,NULL,ARRAY['Around a tenth of the price of a Waza DM-2W','Perfectly usable for slapback and short echoes']::text[],ARRAY['All-plastic construction','Noisy, and the repeats degrade quickly','Not true bypass']::text[],'{}',26,65,NULL,NULL,'{}'),
('alt-trinity','eno-trinity','org-ds-1','ENO Trinity','ENO',30,'A DS-1 in all but name, with a metal box around it.',NULL,NULL,ARRAY['Close copy of the DS-1''s hard-clipping circuit','Metal enclosure and true bypass, which the DS-1 lacks','Cheaper than the original it copies']::text[],ARRAY['Only modestly cheaper — the DS-1 is already a budget pedal','No UK warranty or support','Slightly harsher top end than the Boss']::text[],ARRAY['ENO EX Trinity']::text[],42,85,NULL,NULL,'{}'),
('alt-ultra-drive','mooer-ultra-drive','org-ds-1','Mooer Ultra Drive','Mooer',45,'More modern, tighter high gain in a fraction of the footprint.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/454468.jpg','thomann',ARRAY['Tighter and more modern-voiced than the DS-1 for heavier styles','Micro enclosure saves half the board space','True bypass and solid metal build']::text[],ARRAY['Actually costs less than nothing to save — it''s dearer than a new DS-1','No battery option','Not a like-for-like DS-1 clone; it''s a different flavour of distortion']::text[],'{}',71,72,NULL,NULL,ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/454468.jpg','https://m.media-amazon.com/images/I/61V9EsRf8JL._AC_SL600_.jpg']::text[]),
('alt-fab-1','danelectro-fab-1-distortion','org-ds-1','Danelectro FAB 1 Distortion','Danelectro',15,'Absurdly cheap, and closer to a DS-1 than the price suggests.',NULL,NULL,ARRAY['Roughly a quarter of the price of a DS-1','Voicing lands very close to the Boss original','Light enough to hang off a pedalboard''s spare corner']::text[],ARRAY['Cheap plastic housing that flexes under foot','Battery only — no power jack on most units','Not true bypass']::text[],ARRAY['Danelectro FAB Distortion','Danelectro FAB D-1 Distortion']::text[],74,80,NULL,'Absurd value. Nobody claims it''s built well, but plenty of players say it holds its own against a DS-1 in a mix.','{}')
on conflict (id) do update set
  slug = excluded.slug,
  original_id = excluded.original_id,
  name = excluded.name,
  brand = excluded.brand,
  price_gbp = excluded.price_gbp,
  blurb = excluded.blurb,
  auto_image_url = excluded.auto_image_url,
  image_credit = excluded.image_credit,
  pros = excluded.pros,
  cons = excluded.cons,
  aliases = excluded.aliases,
  popularity = excluded.popularity,
  match_quality = excluded.match_quality,
  search_query = excluded.search_query,
  verdict = excluded.verdict,
  gallery = excluded.gallery;
