insert into public.alternatives
  (id, slug, original_id, name, brand, price_gbp, blurb,
   auto_image_url, image_credit, pros, cons, aliases, popularity,
   match_quality, search_query, verdict, gallery)
values
('alt-eno-bf2','eno-bf-2-flanger','org-bf-2','ENO BF-2 Flanger','ENO',35,'An unapologetic BF-2 clone, right down to the control layout.',NULL,NULL,ARRAY['Control layout mirrors the BF-2, so settings translate one-for-one','Metal enclosure with true bypass','Will self-oscillate on high Resonance like the original does']::text[],ARRAY['Obscure brand with effectively no UK support','Slightly higher noise floor than a genuine BF-2','Resale value is close to zero']::text[],'{}',45,88,NULL,NULL,'{}'),
('alt-uf100','behringer-ultra-flanger-uf100','org-bf-2','Behringer Ultra Flanger UF100','Behringer',30,'Behringer''s BF-2 answer — cheap, and closer than it has any right to be.',NULL,NULL,ARRAY['Gets remarkably close to the BF-2 sweep for well under a fifth of the price','Familiar four-knob layout','Cheap enough to treat as disposable']::text[],ARRAY['Plastic enclosure and switch','Buffered bypass','Thinner low end than the analogue original']::text[],'{}',62,85,NULL,NULL,'{}'),
('alt-turbo-flanger','digitech-turbo-flanger','org-bf-2','DigiTech Turbo Flanger','DigiTech',55,'More extreme sweeps than the BF-2, in a metal chassis.',NULL,NULL,ARRAY['Wider, more extreme sweep range than the original','Genuinely tough metal chassis','Handles high-gain signals without getting muddy']::text[],ARRAY['Discontinued — used only','Voiced more digital and glassy than the analogue BF-2','Larger footprint']::text[],ARRAY['DigiTech Turbo Flanger Pedal']::text[],40,78,NULL,NULL,'{}'),
('alt-e20fl','daphon-e20fl','org-bf-2','Daphon E20FL','Daphon',18,'Barely-there price for a workable flange.',NULL,NULL,ARRAY['About a tenth of what a used BF-2 costs','Perfectly serviceable for occasional flange textures']::text[],ARRAY['All-plastic build','Noisy, especially with the Resonance up','Not true bypass and it dulls your tone when off']::text[],'{}',30,68,NULL,NULL,'{}'),
('alt-thunderstorm','tc-electronic-thunderstorm-flanger','org-bf-2','TC Electronic Thunderstorm Flanger','TC Electronic',49,'Analogue-voiced flange with TonePrint presets from a proper brand.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/400165.jpg','thomann',ARRAY['TonePrint slot lets you load artist-designed flanger settings','Analogue-voiced and warmer than typical budget digital flangers','Real brand with a UK warranty behind it']::text[],ARRAY['TonePrint requires an app and a phone to get the most from it','Fewer hands-on controls than the BF-2','Won''t self-oscillate as wildly as the original']::text[],'{}',70,80,NULL,NULL,ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/400165.jpg','https://m.media-amazon.com/images/I/51BRU1vGgzL._AC_SL600_.jpg']::text[]),
('alt-eno-chorus','eno-chorus','org-ce-2','ENO Chorus','ENO',35,'Straight-down-the-line CE-2 copy with the same two knobs.',NULL,NULL,ARRAY['Same simple Rate/Depth interface as the original','Metal enclosure with true bypass','Warm, single-voice chorus rather than an over-processed digital one']::text[],ARRAY['No UK distribution or support to speak of','Build tolerances vary between units','No resale value']::text[],ARRAY['ENO EX Chorus']::text[],45,86,NULL,NULL,ARRAY['https://m.media-amazon.com/images/I/61Iim4NTKQL._AC_SL600_.jpg']::text[]),
('alt-ch10','biyang-ch10-chorus','org-ce-2','Biyang CH10 Chorus','Biyang',45,'Analogue-flavoured chorus with more controls than the CE-2 offers.',NULL,NULL,ARRAY['Extra controls give finer adjustment than the CE-2''s two knobs','Heavy metal chassis and true bypass','Genuinely lush at slow, deep settings']::text[],ARRAY['Big footprint for a modulation pedal','The extra controls make it slower to dial in than a two-knob CE-2','Patchy support']::text[],ARRAY['Biyang CH-10']::text[],50,84,NULL,NULL,'{}'),
('alt-jf37','joyo-jf-37-analog-chorus','org-ce-2','Joyo JF-37 Analog Chorus','Joyo',32,'Warm analogue-voiced chorus in a metal box for pocket money.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/529964.jpg','thomann',ARRAY['Warm, analogue-leaning voicing that sits close to CE-2 territory','Metal enclosure and true bypass at a very low price','Simple enough to set by ear in seconds']::text[],ARRAY['A touch brighter and thinner than a genuine CE-2','Some units have an audible click on switching','Full-size box takes standard board space']::text[],'{}',72,85,NULL,NULL,ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/529964.jpg','https://m.media-amazon.com/images/I/61rUexeVpHL._AC_SL600_.jpg']::text[]),
('alt-ensemble','mooer-ensemble-chorus','org-ce-2','Mooer Ensemble Chorus','Mooer',45,'Analogue BBD chorus squeezed into a micro enclosure.','https://m.media-amazon.com/images/I/51vChAHnPIL._AC_SL600_.jpg','amazon',ARRAY['True analogue BBD circuit, not a digital emulation','Micro size frees up serious board space next to a compact Boss box','Adds a Level control the CE-2 doesn''t have']::text[],ARRAY['No battery option','Top-mounted jacks affect cable routing','Tiny knobs make fine adjustment awkward']::text[],'{}',84,87,NULL,NULL,ARRAY['https://m.media-amazon.com/images/I/51vChAHnPIL._AC_SL600_.jpg','https://m.media-amazon.com/images/I/61zK-MmUInL._AC_SL600_.jpg']::text[]),
('alt-multi-chorus','digitech-multi-chorus','org-ce-2','DigiTech Multi Chorus','DigiTech',55,'Several chorus voices where the CE-2 gives you one.',NULL,NULL,ARRAY['Multiple chorus voicings rather than the CE-2''s single character','Tough metal chassis','Stereo output for wider clean sounds']::text[],ARRAY['Discontinued — used only','Cleaner and more digital-sounding than the warm CE-2','Bigger and heavier']::text[],ARRAY['DigiTech Multi Chorus Pedal']::text[],42,76,NULL,NULL,'{}'),
('alt-uc200','behringer-ultra-chorus-uc200','org-ce-2','Behringer Ultra Chorus UC200','Behringer',25,'The cheapest credible route to a classic Boss chorus sound.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/111469.jpg','thomann',ARRAY['Close copy of the classic Boss chorus circuit','Costs roughly a tenth of a used CE-2','Familiar knob layout']::text[],ARRAY['Plastic enclosure and switch','Buffered bypass','Slightly noisier and brighter than the original']::text[],'{}',68,83,NULL,NULL,ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/111469.jpg','https://m.media-amazon.com/images/I/71GhT59TzbL._AC_SL600_.jpg','https://m.media-amazon.com/images/I/61wgfg61nUL._AC_SL600_.jpg','https://m.media-amazon.com/images/I/516WFKGZ05L._AC_SL600_.jpg']::text[]),
('alt-e20ch','daphon-e20ch','org-ce-2','Daphon E20CH','Daphon',18,'Rock-bottom price, surprisingly listenable chorus.',NULL,NULL,ARRAY['Cheapest chorus on this list by a distance','Fine for recording where you can EQ around its limitations']::text[],ARRAY['All-plastic construction','Audible noise floor','Not true bypass']::text[],'{}',28,66,NULL,NULL,'{}')
on conflict (id) do update set
  slug = excluded.slug,
  original_id = excluded.original_id,
  name = excluded.name,
  brand = excluded.brand,
  price_gbp = excluded.price_gbp,
  blurb = excluded.blurb,
  auto_image_url = excluded.auto_image_url,
  image_credit = excluded.image_credit,
  pros = excluded.pros,
  cons = excluded.cons,
  aliases = excluded.aliases,
  popularity = excluded.popularity,
  match_quality = excluded.match_quality,
  search_query = excluded.search_query,
  verdict = excluded.verdict,
  gallery = excluded.gallery;
