insert into public.alternatives
  (id, slug, original_id, name, brand, price_gbp, blurb,
   auto_image_url, image_credit, pros, cons, aliases, popularity,
   match_quality, search_query, verdict, gallery)
values
('alt-hot-head','digitech-hot-head','org-ds-1','DigiTech Hot Head','DigiTech',35,'Higher-gain distortion with a proper three-band EQ.',NULL,NULL,ARRAY['Full three-band EQ where the DS-1 gives you a single Tone knob','Considerably more gain on tap than the Boss','Metal chassis']::text[],ARRAY['Discontinued — used market only','Bulkier than a compact Boss enclosure','Voiced more scooped and modern than a DS-1']::text[],ARRAY['DigiTech Hot Head Distortion']::text[],46,76,NULL,NULL,'{}'),
('alt-e20ds','daphon-e20ds','org-ds-1','Daphon E20DS','Daphon',18,'The floor price for a hard-clipping distortion.',NULL,NULL,ARRAY['About a third of the price of a new DS-1','Usable distortion voicing for practice and demos']::text[],ARRAY['All-plastic construction including the footswitch','Noticeable hiss','Not true bypass']::text[],'{}',30,72,NULL,NULL,'{}'),
('alt-eq7','biyang-eq7','org-ge-7','Biyang EQ7','Biyang',45,'Seven-band EQ with a quieter noise floor than the Boss.',NULL,NULL,ARRAY['Same seven-band layout, so GE-7 settings transfer directly','Quieter than the GE-7, whose noise floor is its main weakness','Metal chassis and true bypass']::text[],ARRAY['Larger footprint than a compact Boss pedal','Sliders feel less precise than the Boss ones','Limited UK support']::text[],ARRAY['Biyang EQ-7']::text[],47,88,NULL,NULL,'{}'),
('alt-eq700','behringer-eq700','org-ge-7','Behringer EQ700','Behringer',25,'A GE-7 copy for less than a quarter of the price.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/183479.jpg','thomann',ARRAY['Seven bands with the same frequency centres as the GE-7','Roughly a quarter of the price of the Boss','Sliders travel well and hold their position']::text[],ARRAY['Plastic enclosure that flexes if you stand on it','Buffered bypass','Slightly noisier than the Boss, which was already noisy']::text[],'{}',76,90,NULL,'Does the GE-7''s job for a quarter of the money. The plastic case is the only real complaint.',ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/183479.jpg','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/183515.jpg','https://m.media-amazon.com/images/I/618I2dfZitL._AC_SL600_.jpg','https://m.media-amazon.com/images/I/51AWjIi6QkL._AC_SL600_.jpg']::text[]),
('alt-fish-n-chips','danelectro-fish-n-chips','org-ge-7','Danelectro Fish ''n'' Chips','Danelectro',29,'Cult seven-band EQ that costs less than a set of strings.',NULL,NULL,ARRAY['Long-standing cult favourite for taming acoustic pickups and boxy amps','Very small footprint for a seven-band EQ','Cheap enough to buy two']::text[],ARRAY['Plastic housing and fragile sliders','Not true bypass','Slider caps come off easily']::text[],ARRAY['Danelectro Fish and Chips']::text[],72,82,NULL,NULL,'{}'),
('alt-e20ge','daphon-e20ge','org-ge-7','Daphon E20GE','Daphon',18,'Bargain-basement graphic EQ that does the job.',NULL,NULL,ARRAY['Cheapest graphic EQ pedal you''ll find','Enough range to fix a problem frequency']::text[],ARRAY['All-plastic build','Audible noise once you boost anything','Not true bypass']::text[],'{}',24,70,NULL,NULL,'{}'),
('alt-sf300','behringer-sf300-super-fuzz','org-fz-2','Behringer SF300 Super Fuzz','Behringer',29,'The clone that made a rare, expensive fuzz available to everyone.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/115985.jpg','thomann',ARRAY['Near-direct copy of the FZ-2, including both Gain modes and the two-band EQ','One of the most celebrated budget pedals ever made — a genuine cult classic','Around a fifth of what a used FZ-2 costs']::text[],ARRAY['Plastic enclosure that won''t take heavy stage abuse','Buffered bypass rather than true bypass','Battery compartment requires a screwdriver on some units']::text[],'{}',91,88,NULL,'A genuine cult classic. Frequently described as the best-value fuzz ever made, and the reason most players never bother hunting an FZ-2.',ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/115985.jpg','https://m.media-amazon.com/images/I/71BUcnNZ6fL._AC_SL600_.jpg']::text[]),
('alt-hm300','behringer-hm300-heavy-distortion','org-hm-2','Behringer HM300 Heavy Distortion','Behringer',29,'The chainsaw tone for £29 — the most famous budget clone of them all.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/204415.jpg','thomann',ARRAY['Gets genuinely close to the HM-2 buzzsaw with all knobs fully clockwise','Same two-band Colour EQ layout as the original','A fifth of the price of a Waza HM-2W, and a fraction of a vintage unit']::text[],ARRAY['Plastic enclosure and footswitch','Buffered bypass','A little less low-end weight than a genuine HM-2']::text[],'{}',93,90,NULL,'The single most recommended budget clone in guitar forums. Owners agree it gets you most of the way to the HM-2 chainsaw for a twentieth of the price of a vintage unit.',ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/204415.jpg','https://m.media-amazon.com/images/I/811hgVpK21L._AC_SL600_.jpg','https://m.media-amazon.com/images/I/51AO6KdL3dL._AC_SL600_.jpg']::text[]),
('alt-oct1','eno-octaver-oct-1','org-oc-2','ENO Octaver OCT-1','ENO',32,'Straight OC-2 copy with the same three-knob blend.',NULL,NULL,ARRAY['Same Direct / Oct 1 / Oct 2 layout, so OC-2 settings transfer directly','Analogue tracking with the same rubbery character','Metal enclosure and true bypass']::text[],ARRAY['Tracking glitches lower down the neck, as the original does','No UK distribution or support','Noticeable noise floor with both octaves up']::text[],'{}',41,84,NULL,NULL,'{}'),
('alt-so400','behringer-super-octaver-so400','org-oc-2','Behringer Super Octaver SO400','Behringer',29,'The cheapest way into real analogue sub-octave territory.',NULL,NULL,ARRAY['Close copy of the OC-2 circuit at roughly a quarter of the price','Identical control layout','Tracks about as well as the original on single notes']::text[],ARRAY['Plastic enclosure and footswitch','Buffered bypass','Struggles badly below the fifth fret — as does the pedal it copies']::text[],ARRAY['Behringer SO400']::text[],77,88,NULL,NULL,'{}'),
('alt-pure-octave','mooer-pure-octave','org-oc-2','Mooer Pure Octave','Mooer',59,'Eleven octave modes and polyphonic tracking in a micro box.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/315629.jpg','thomann',ARRAY['Polyphonic — it handles full chords, which the OC-2 simply cannot','Eleven modes including octave-up and multi-octave combinations','Micro footprint and true bypass']::text[],ARRAY['Digital, so it lacks the analogue grit that makes the OC-2 distinctive','No battery option','Twice the price of the Behringer clone']::text[],'{}',80,76,NULL,NULL,ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/315629.jpg','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/573087.jpg']::text[]),
('alt-nether','tc-electronic-nether-octaver','org-oc-2','TC Electronic Nether Octaver','TC Electronic',49,'Clean, fast sub-octave tracking from a proper brand.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/435997.jpg','thomann',ARRAY['Tracks faster and more accurately than the OC-2','Real UK warranty and support behind it','Two independent sub-octave levels plus dry blend']::text[],ARRAY['Cleaner and more clinical than the original''s rubbery analogue character','No octave-up option','Slightly larger than a micro pedal']::text[],ARRAY['TC Electronic Nether Octaver']::text[],72,80,NULL,NULL,ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/435997.jpg']::text[])
on conflict (id) do update set
  slug = excluded.slug,
  original_id = excluded.original_id,
  name = excluded.name,
  brand = excluded.brand,
  price_gbp = excluded.price_gbp,
  blurb = excluded.blurb,
  auto_image_url = excluded.auto_image_url,
  image_credit = excluded.image_credit,
  pros = excluded.pros,
  cons = excluded.cons,
  aliases = excluded.aliases,
  popularity = excluded.popularity,
  match_quality = excluded.match_quality,
  search_query = excluded.search_query,
  verdict = excluded.verdict,
  gallery = excluded.gallery;
