insert into public.alternatives
  (id, slug, original_id, name, brand, price_gbp, blurb,
   auto_image_url, image_credit, pros, cons, aliases, popularity,
   match_quality, search_query, verdict, gallery)
values
('alt-to800','behringer-to800-vintage-overdrive','org-tube-screamer','Behringer TO800 Vintage Overdrive','Behringer',25,'A near-direct TS808 copy in a plastic shell — same op-amp, a fraction of the price.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/183774.jpg','thomann',ARRAY['Uses the same JRC4558D op-amp chip as the original TS808','Circuit is a close copy — the mid-hump and clipping feel genuinely track the original','The cheapest way into a real Tube Screamer circuit, full stop']::text[],ARRAY['Plastic enclosure won''t survive being stamped on night after night','Buffered bypass rather than true bypass','Fiddly battery compartment and a cheap-feeling footswitch']::text[],'{}',88,92,NULL,'The consensus budget pick. Owners consistently say it sounds like a Tube Screamer and feels like a toy — the circuit is right, the box isn''t. Most advise buying it, then rehousing it if you gig.',ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/183774.jpg','https://m.media-amazon.com/images/I/71sJub23+WL._AC_SL600_.jpg','https://m.media-amazon.com/images/I/51AO6KdL3dL._AC_SL600_.jpg','https://m.media-amazon.com/images/I/61V9Ok+lKmL._AC_SL600_.jpg']::text[]),
('alt-jf01','joyo-jf-01-vintage-overdrive','org-tube-screamer','Joyo JF-01 Vintage Overdrive','Joyo',29,'The TS clone that puts a metal box and true bypass around the same idea.','https://m.media-amazon.com/images/I/61YwK3tDchL._AC_SL600_.jpg','amazon',ARRAY['Full metal enclosure for barely more than the plastic Behringer','True bypass switching keeps it out of your signal path when off','Mid-hump and compression track a TS9 closely']::text[],ARRAY['Noticeably noisier than the original at high gain settings','Painted graphics scuff and wear over time','Standard-size box eats as much board space as the pedal it replaces']::text[],'{}',82,90,NULL,'Widely recommended as the sensible upgrade over the Behringer: same idea, metal enclosure, true bypass. Noise at high gain is the recurring complaint.',ARRAY['https://m.media-amazon.com/images/I/617HHxdZEoL._AC_SL600_.jpg']::text[]),
('alt-green-mile','mooer-green-mile','org-tube-screamer','Mooer Green Mile','Mooer',45,'Micro-sized TS with a hot mode that goes further than the original.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/309295.jpg','thomann',ARRAY['Micro enclosure frees up roughly half the board space of a TS9','Two modes — ''warm'' for classic TS, ''hot'' for more gain than the original has','Solid metal housing with true bypass']::text[],ARRAY['No battery option — it''s 9V adapter only','Top-mounted jacks change how you have to cable your board','Small knobs are hard to nudge with your foot mid-set']::text[],'{}',90,85,NULL,'Praised almost universally for build quality and the board space it saves. The Hot mode is what wins people over — it goes further than a real TS9.',ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/309295.jpg','https://m.media-amazon.com/images/I/5126kA+ttOL._AC_SL600_.jpg','https://m.media-amazon.com/images/I/4155vAh6UIL._AC_SL600_.jpg']::text[]),
('alt-od8','biyang-od-8','org-tube-screamer','Biyang OD-8 / OD-10','Biyang',45,'Socketed op-amp means you can retune the drive with a £2 chip swap.',NULL,NULL,ARRAY['Socketed op-amp — drop in a JRC4558, TL072 or RC4558 to change the character','Heavy-duty metal chassis and true bypass','Tighter, cleaner low end than most budget clones manage']::text[],ARRAY['Noticeably larger and heavier than a TS9 on a crowded board','Patchy UK distribution and support','Dated graphics next to the original']::text[],ARRAY['Biyang OD-8']::text[],65,88,NULL,NULL,'{}'),
('alt-bad-monkey','digitech-bad-monkey','org-tube-screamer','Digitech Bad Monkey','DigiTech',60,'The cult TS variant with proper bass and treble controls.',NULL,NULL,ARRAY['Separate bass and treble controls give far more tone shaping than the original''s single Tone knob','Mixer/direct out lets you run straight to a desk','Widely regarded as the best-sounding budget TS-style pedal ever made']::text[],ARRAY['Discontinued — used market only, and prices are climbing every year','Plastic body and jacks','Voiced a little darker than a true TS9']::text[],ARRAY['DigiTech Bad Monkey Overdrive']::text[],86,80,NULL,'Something of a legend. Players rate it above the pedal it clones because of the separate bass and treble controls. Prices have climbed steadily since it was discontinued.',ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/632331.jpg','https://m.media-amazon.com/images/I/81LrQVdKRLL._AC_SL600_.jpg']::text[]),
('alt-tc-cream','tone-city-cream','org-tube-screamer','Tone City Cream','Tone City',39,'Lower-gain, more transparent take — a great always-on.',NULL,NULL,ARRAY['Tiny footprint, all-metal build, true bypass','More transparent and lower gain than a TS9 — works as an always-on tone thickener','Cleans up well with the guitar''s volume control']::text[],ARRAY['Less output on tap than the original if you want it as a lead boost','No battery option','Micro knobs are fiddly to set precisely']::text[],ARRAY['Tone City Cream Overdrive']::text[],60,78,NULL,NULL,ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/537704.jpg','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/624438.jpg']::text[]),
('alt-cp73','caline-cp-73','org-tube-screamer','Caline CP-73','Caline',32,'Aluminium-housed TS clone that punches above its price.',NULL,NULL,ARRAY['Aluminium alloy housing feels far sturdier than the price suggests','True bypass switching','Low noise floor for the money']::text[],ARRAY['Build quality varies noticeably between units','Power jack placement is awkward on a tightly packed board','Effectively no UK warranty support']::text[],ARRAY['Caline CP-73 Overdrive']::text[],55,82,NULL,NULL,'{}'),
('alt-e20od','daphon-e20od','org-tube-screamer','Daphon E20OD','Daphon',18,'The absolute floor price for a Tube Screamer voicing.',NULL,NULL,ARRAY['Around a tenth of the price of the original','Core overdrive voicing is genuinely usable for practice or recording']::text[],ARRAY['All-plastic construction, including the footswitch','Audible hiss once you push the gain','Not true bypass, and it colours your signal even when switched off']::text[],'{}',40,70,NULL,NULL,'{}'),
('alt-screaming-blues','digitech-screaming-blues','org-bd-2','DigiTech Screaming Blues','DigiTech',45,'Two voicings in one metal box, if you can find one used.',NULL,NULL,ARRAY['Two distinct voicings give more range than the single-channel BD-2','All-metal chassis built like a tank','Used prices are still low because the brand is out of fashion']::text[],ARRAY['Discontinued — used market only','Not true bypass','Bulkier than the BD-2 it replaces']::text[],ARRAY['DigiTech Screaming Blues Overdrive']::text[],55,82,NULL,NULL,'{}'),
('alt-bo100','behringer-blues-overdrive-bo100','org-bd-2','Behringer Blues Overdrive BO100','Behringer',25,'A close BD-2 copy for the price of a set of strings.',NULL,NULL,ARRAY['Circuit is a close copy — the dynamic, amp-like breakup really is there','Same three-knob layout, so BD-2 settings translate directly','Cheapest possible route to this sound']::text[],ARRAY['Plastic enclosure','Buffered bypass rather than true bypass','Fizzier and brighter than the original at maximum gain']::text[],ARRAY['Behringer BO100']::text[],78,90,NULL,NULL,'{}'),
('alt-bl8','biyang-bl-8-blue','org-bd-2','Biyang BL-8 Blue','Biyang',45,'Metal-built BD-2 alternative with a swappable op-amp.',NULL,NULL,ARRAY['Socketed op-amp for tone tweaking without a soldering iron','Rugged metal build with true bypass','Handles low end better than the BD-2''s slightly thin bass response']::text[],ARRAY['Large footprint compared to a compact Boss box','Sparse documentation and support','Heavier than the original']::text[],ARRAY['Biyang BL-8']::text[],50,85,NULL,NULL,'{}'),
('alt-blues-mood','mooer-blues-mood','org-bd-2','Mooer Blues Mood','Mooer',45,'Micro BD-2 that covers stock and Keeley-modded territory.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/315657.jpg','thomann',ARRAY['Multiple voicing modes cover both stock and Keeley-mod BD-2 ground','Micro size saves serious pedalboard real estate','True bypass and all-metal construction']::text[],ARRAY['No battery option','The mode switch isn''t something you''ll change mid-song','Top-mounted jacks change your cable routing']::text[],'{}',80,84,NULL,'Regarded as covering both stock and Keeley-modded BD-2 ground. The size is the main draw.',ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/315657.jpg','https://m.media-amazon.com/images/I/71ZOp3S7WcL._AC_SL600_.jpg']::text[])
on conflict (id) do update set
  slug = excluded.slug,
  original_id = excluded.original_id,
  name = excluded.name,
  brand = excluded.brand,
  price_gbp = excluded.price_gbp,
  blurb = excluded.blurb,
  auto_image_url = excluded.auto_image_url,
  image_credit = excluded.image_credit,
  pros = excluded.pros,
  cons = excluded.cons,
  aliases = excluded.aliases,
  popularity = excluded.popularity,
  match_quality = excluded.match_quality,
  search_query = excluded.search_query,
  verdict = excluded.verdict,
  gallery = excluded.gallery;
