insert into public.alternatives
  (id, slug, original_id, name, brand, price_gbp, blurb,
   auto_image_url, image_credit, pros, cons, aliases, popularity,
   match_quality, search_query, verdict, gallery)
values
('alt-uv300','behringer-uv300-ultra-vibrato','org-vb-2','Behringer UV300 Ultra Vibrato','Behringer',29,'A VB-2 clone for a fraction of what the original commands.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/115986.jpg','thomann',ARRAY['Genuine pitch vibrato, not a chorus pretending to be one','Includes the Rise Time control that makes the VB-2 special','Around a seventh of the price of a Waza VB-2W']::text[],ARRAY['Plastic enclosure and footswitch','Buffered bypass','Thinner than the original at deep settings']::text[],ARRAY['Behringer UV300']::text[],74,87,NULL,NULL,ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/115986.jpg']::text[]),
('alt-jf32','joyo-jf-32-hot-plexi','org-plexitone','Joyo JF-32 Hot Plexi','Joyo',39,'Marshall-in-a-box crunch for the price of a patch cable.','https://m.media-amazon.com/images/I/61XZQYcvRYL._AC_SL600_.jpg','amazon',ARRAY['Convincing British crunch through a clean amp','Metal enclosure and true bypass','A fifth of the price of the Plexitone']::text[],ARRAY['Only one gain channel, where the Plexitone footswitches two','Runs on 9V, so it lacks the original''s internal 12V headroom','Gets fizzy at maximum drive']::text[],ARRAY['Joyo Hot Plexi']::text[],70,80,NULL,NULL,'{}'),
('alt-englishman','caline-englishman','org-plexitone','Caline Englishman','Caline',35,'Plexi-voiced overdrive with a surprisingly good EQ section.',NULL,NULL,ARRAY['Three-band EQ gives more shaping than most amp-in-a-box pedals','Aluminium housing that feels well above its price','True bypass']::text[],ARRAY['Build consistency varies between units','Single gain stage only','Effectively no UK warranty support']::text[],'{}',54,76,NULL,NULL,'{}'),
('alt-golden-plexi','tone-city-golden-plexi','org-plexitone','Tone City Golden Plexi','Tone City',45,'Micro-sized Plexi drive that cleans up like the real thing.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/622905.jpg','thomann',ARRAY['Responds to guitar volume almost as well as the Plexitone does','Tiny footprint for a full amp-in-a-box sound','All-metal build and true bypass']::text[],ARRAY['No battery option','Micro knobs are hard to set precisely','Less low-end authority than the 12V Plexitone']::text[],ARRAY['Tone City Golden Plexi V3']::text[],68,82,NULL,NULL,ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/622905.jpg']::text[]),
('alt-mosky-plexi','mosky-plexi-distortion','org-plexitone','Mosky Plexi Distortion','Mosky',29,'The cheapest credible route to a Plexi stack sound.','https://m.media-amazon.com/images/I/71cYh+sWtzL._AC_SL600_.jpg','amazon',ARRAY['Genuine British crunch voicing for under thirty pounds','Metal enclosure and true bypass','Small enough to fill a gap on a full board']::text[],ARRAY['Noisier than the alternatives here','Basic single-knob tone control','Brand support is essentially non-existent']::text[],'{}',52,74,NULL,NULL,'{}'),
('alt-jf09','joyo-jf-09-tremolo','org-tremulator','Joyo JF-09 Tremolo','Joyo',29,'Simple two-knob tremolo that gets the essentials right.','https://m.media-amazon.com/images/I/61n3J4IXQdL._AC_SL600_.jpg','amazon',ARRAY['Smooth, rounded pulse rather than a hard digital chop','Same two-control simplicity as the Tremulator','Metal enclosure and true bypass']::text[],ARRAY['Volume drops slightly when engaged','Not as organic as the Demeter''s optical circuit','Full-size box for a two-knob pedal']::text[],ARRAY['Joyo Tremolo']::text[],66,78,NULL,NULL,'{}'),
('alt-trelicopter','mooer-trelicopter','org-tremulator','Mooer Trelicopter','Mooer',45,'Optical tremolo in a micro enclosure, with a bias control.','https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/312674.jpg','thomann',ARRAY['Genuine optical circuit, the same principle as the Tremulator','Adds a Bias control the Demeter doesn''t have, for waveform shaping','Frees up serious board space']::text[],ARRAY['No battery option','Micro knobs make matching a tempo fiddly','No tap tempo']::text[],'{}',78,84,NULL,NULL,ARRAY['https://thumbs.static-thomann.de/thumb/thumb600x600/pics/prod/312674.jpg']::text[]),
('alt-cool-cat-trem','danelectro-cool-cat-tremolo','org-tremulator','Danelectro Cool Cat Tremolo','Danelectro',39,'Warm, deep tremolo with more range than you''d expect.',NULL,NULL,ARRAY['Goes from a gentle shimmer to full helicopter chop','Metal chassis, unlike Danelectro''s cheaper FAB line','True bypass']::text[],ARRAY['Discontinued — used market only','Larger footprint than a micro pedal','Slight tick audible at slow speeds on some units']::text[],'{}',50,79,NULL,NULL,'{}'),
('alt-ginean-massive','ginean-massive-distortion','org-boneshaker','Ginean Massive Distortion','Ginean',45,'High-gain distortion with proper EQ control for half the money.',NULL,NULL,ARRAY['Three-band EQ, so it keeps the Boneshaker''s main advantage','Plenty of gain on tap for modern metal','Roughly a third of the price of the original']::text[],ARRAY['Obscure brand with almost no UK presence','No sweepable midrange, which is the Boneshaker''s best feature','Resale value close to zero']::text[],'{}',34,72,NULL,NULL,'{}'),
('alt-hairy-show','ginean-hairy-show-fuzz','org-carcosa','Ginean Hairy Show Fuzz','Ginean',45,'Gated, spluttering fuzz for a third of the Carcosa''s price.',NULL,NULL,ARRAY['Gets the gated, dying-battery splutter the Carcosa is built around','Includes a bias control for starving the circuit','Roughly a third of the price of the original']::text[],ARRAY['Only one voicing, where the Carcosa switches between two','Obscure brand with no UK support','Noisier than the DOD at extreme bias settings']::text[],'{}',32,74,NULL,NULL,'{}'),
('alt-gesi-face','jrr-gesi-face','org-fuzz-face','JRR GeSi Face','JRR',59,'Germanium and silicon Fuzz Face in one box.',NULL,NULL,ARRAY['Switches between germanium and silicon voicings — two pedals in one','Hand-built with selected transistors','Less than half the price of two Dunlop Fuzz Face Minis']::text[],ARRAY['Small-workshop brand, so availability comes and goes','No true-bypass option on some builds','Still fussy about what sits in front of it, like the original']::text[],'{}',30,84,NULL,NULL,'{}'),
('alt-tiny-fuzz','mas-effects-tiny-fuzz','org-fuzz-face','Mas Effects Tiny Fuzz','Mas Effects',49,'A Fuzz Face circuit shrunk into a micro enclosure.',NULL,NULL,ARRAY['Fits a classic two-transistor fuzz into a fraction of the board space','Cleans up from the guitar volume like the original does','Considerably cheaper than a Dunlop']::text[],ARRAY['Micro knobs make the narrow sweet spot harder to find','No battery option','Limited availability']::text[],'{}',34,80,NULL,NULL,'{}')
on conflict (id) do update set
  slug = excluded.slug,
  original_id = excluded.original_id,
  name = excluded.name,
  brand = excluded.brand,
  price_gbp = excluded.price_gbp,
  blurb = excluded.blurb,
  auto_image_url = excluded.auto_image_url,
  image_credit = excluded.image_credit,
  pros = excluded.pros,
  cons = excluded.cons,
  aliases = excluded.aliases,
  popularity = excluded.popularity,
  match_quality = excluded.match_quality,
  search_query = excluded.search_query,
  verdict = excluded.verdict,
  gallery = excluded.gallery;
