-- ---------------------------------------------------------------------------
-- Catalogue expansion: 11 more originals (8 pedals, 3 amps) and 16 budget
-- alternatives against them.
--
-- Run this in the Supabase SQL editor. Safe to run twice: every insert is
-- `on conflict (id) do nothing`, so a partial run can be repeated.
--
-- Checked against the 35 originals and 96 alternatives already in the database
-- before writing, which is why this is smaller than it first looks. The
-- obvious budget options for these circuits - Mooer AnaEcho, Trelicopter,
-- Ninety Orange, ShimVerb, Ensemble King, Joyo JF-06/JF-09/JF-317, Behringer
-- VD400/UC200, Donner Yellow Fall and Harmonic Square, Harley Benton TUBE15
-- Celestion, Bugera V5 - are all already in the catalogue against other
-- originals, and `slug` is unique across the alternatives table, so they
-- cannot be listed twice. Only genuinely new products are added here.
--
-- The Vox AC15C1 is deliberately NOT added as an original: it is already in
-- the catalogue as a budget alternative to the AC30, and having it be both
-- would give it two pages saying opposite things about it.
--
-- Photos are left NULL. Run `npm run images` after this to populate
-- `auto_image_url`, or paste URLs into `image_url` from the admin (which takes
-- precedence). Prices are approximate UK street prices.
-- ---------------------------------------------------------------------------

-- Originals -----------------------------------------------------------------

insert into public.originals
  (id, slug, name, brand, category, price_gbp, blurb, description,
   image_credit, tags, artists, aliases, popularity, search_query)
values

('org-sd-1','boss-sd-1-super-overdrive','Boss SD-1 Super Overdrive','Boss','overdrive',59,'Asymmetric clipping and a mid-hump - the yellow box on a million pedalboards.','The SD-1 is the Tube Screamer''s stablemate rather than its rival: the same basic idea, but with asymmetric diode clipping that leaves a little more grit and a little less compression. It has been in continuous production since 1981, which makes it one of the cheapest genuinely iconic pedals you can buy new. Most players use it the way a TS gets used - low gain, high level, shoved into an already-breaking amp to tighten the low end and push the mids forward.',NULL,ARRAY['sd1','sd-1','super overdrive','boss','yellow','overdrive','asymmetric','mid hump']::text[],ARRAY['Zakk Wylde','Eddie Van Halen','Prince']::text[],'{}',88,'Boss SD-1 Super Overdrive'),

('org-dyna-comp','mxr-dyna-comp','MXR Dyna Comp','MXR','eq',109,'The squashy Nashville compressor - the sound of a snapped country lick.','The Dyna Comp is built around an OTA compressor circuit that does not so much control dynamics as flatten them into a distinctive squashed pop. That is the appeal: it is not a transparent studio compressor, it is an effect. Two knobs, no attack or release, and a noticeable noise floor - and it has still been on country and pop pedalboards continuously since 1972, because nothing else sounds quite like it.',NULL,ARRAY['dyna comp','dynacomp','compressor','mxr','squash','sustain','country','nashville']::text[],ARRAY['David Gilmour','Brad Paisley','Johnny Marr']::text[],'{}',82,'MXR Dyna Comp compressor'),

('org-small-clone','electro-harmonix-small-clone','Electro-Harmonix Small Clone','Electro-Harmonix','modulation',89,'The thick analogue chorus behind Come As You Are.','A single-knob analogue chorus with a depth switch, and famous almost entirely because of one riff. The Small Clone''s character is a wide, watery warble that sits deeper than most choruses - it does not do subtle, which is exactly why it works on a clean neck pickup. Bucket-brigade chips do the work, which is also why it adds a little warmth, and a little noise, that digital choruses do not.',NULL,ARRAY['small clone','chorus','ehx','electro harmonix','nirvana','analogue chorus','bucket brigade']::text[],ARRAY['Kurt Cobain','John Frusciante','Andy Summers']::text[],'{}',80,'Electro-Harmonix Small Clone chorus'),

('org-tr-2','boss-tr-2-tremolo','Boss TR-2 Tremolo','Boss','modulation',95,'Amp-style volume tremolo in the standard Boss box.','Tremolo is the oldest effect in the guitar canon - amplitude modulation, nothing more - and the TR-2 is the most common way to get it onto a board. Rate, Depth and Wave, with the wave control sweeping from a soft triangle to something close to a square-wave chop. The known trade-off is a perceived volume drop when the depth is up, which is why plenty of players run it into a clean boost.',NULL,ARRAY['tr2','tr-2','tremolo','boss','trem','amplitude','chop']::text[],ARRAY['Jonny Greenwood','Dan Auerbach']::text[],'{}',74,'Boss TR-2 Tremolo'),

('org-ph-3','boss-ph-3-phase-shifter','Boss PH-3 Phase Shifter','Boss','modulation',119,'Four, eight, ten and twelve-stage phasing, plus tap tempo.','Where a Phase 90 gives you one sweep and one knob, the PH-3 gives you 4-, 8-, 10- and 12-stage modes plus rising and falling settings that sweep in one direction forever, Shepard-tone style. It is the phaser for players who want the effect to be a feature rather than a texture, and the tap tempo makes it usable across a set without re-dialling between songs.',NULL,ARRAY['ph3','ph-3','phaser','phase shifter','boss','modulation','tap tempo']::text[],ARRAY['The Edge','Nile Rodgers']::text[],'{}',72,'Boss PH-3 Phase Shifter'),

('org-whammy','digitech-whammy','DigiTech Whammy','DigiTech','octave',279,'The pitch-shifting treadle that defined a decade of guitar.','A rocker pedal that sweeps pitch rather than volume or wah. Set it two octaves up and you get the squealing dive-bomb that ran through the whole of the late nineties; set it to a harmony interval and it becomes a one-man twin-guitar rig. Tracking on the older models is famously imperfect on chords, which players long ago decided was character rather than fault.',NULL,ARRAY['whammy','digitech','pitch shift','octave','harmoniser','harmonizer','dive bomb','treadle']::text[],ARRAY['Tom Morello','Jack White','Matt Bellamy','Jonny Greenwood']::text[],'{}',78,'DigiTech Whammy pedal'),

('org-memory-man','electro-harmonix-deluxe-memory-man','Electro-Harmonix Deluxe Memory Man','Electro-Harmonix','delay',299,'Analogue delay with chorus on the repeats - the sound of early U2.','A bucket-brigade delay whose repeats darken and blur as they decay, with a modulation section that adds chorus or vibrato to the tail. That combination is the whole point: the repeats do not simply fade, they drift slightly out of tune, and that is what gives the effect its depth. Around 550ms of delay, and a warmth that digital units spend a lot of DSP trying to model.',NULL,ARRAY['memory man','deluxe memory man','dmm','ehx','analogue delay','analog delay','bucket brigade','u2','chorus delay']::text[],ARRAY['The Edge','Jack White','Kevin Shields']::text[],'{}',80,'Electro-Harmonix Deluxe Memory Man'),

('org-bluesky','strymon-bluesky','Strymon blueSky','Strymon','reverb',349,'The studio-grade reverb most boutique pedals get measured against.','Three machines - plate, room and spring - each with normal, modulated and shimmer modes, running on a SHARC DSP chip closer to a rack unit than a stompbox. The blueSky''s reputation rests largely on the shimmer setting, which feeds a pitched octave into the reverb tail and turns a held chord into something orchestral. Expensive, and generally reckoned to be worth it.',NULL,ARRAY['bluesky','blue sky','strymon','reverb','shimmer','plate','spring','ambient']::text[],ARRAY['John Mayer','Ed O''Brien']::text[],'{}',76,'Strymon blueSky reverb'),

('org-deluxe-reverb','fender-65-deluxe-reverb','Fender ''65 Deluxe Reverb','Fender','amp',1349,'22 watts of the most recorded clean tone in history.','The Deluxe Reverb is the reference point for American clean tone: a 22-watt valve combo with a 12" speaker, spring reverb and Fender''s own tube vibrato. It starts to break up somewhere around 5 on the dial, which is loud enough to be a problem in a small room and exactly right on a stage. Every modelling amp on the market ships with a preset trying to be this.',NULL,ARRAY['deluxe reverb','fender','drri','65 deluxe','valve amp','tube amp','clean','blackface','combo']::text[],ARRAY['John Mayer','Jonny Greenwood','Mike Campbell']::text[],'{}',92,'Fender 65 Deluxe Reverb reissue amp'),

('org-jcm800','marshall-jcm800-2203','Marshall JCM800 2203','Marshall','amp',1899,'The 100-watt head that is simply what rock guitar sounds like.','A single-channel, master-volume 100-watt valve head from 1981, and the backbone of eighties rock and thrash. There is no channel switching and no effects loop worth speaking of - you set it where it sounds good and use your guitar volume for the rest. The midrange push, and the way it cleans up under your fingers, are why players still put up with the weight and the volume.',NULL,ARRAY['jcm800','2203','marshall','valve head','tube amp','rock','metal','master volume','80s']::text[],ARRAY['Slash','Zakk Wylde','Kerry King','Noel Gallagher']::text[],'{}',90,'Marshall JCM800 2203 head'),

('org-twin-reverb','fender-65-twin-reverb','Fender ''65 Twin Reverb','Fender','amp',1699,'85 watts of clean headroom that will not break up for anyone.','Two 12" speakers, 85 valve watts, and a clean stage that stays clean at volumes no venue will let you reach. That is the Twin''s job: it is a pedal platform and a jazz amp, not an overdrive machine. If you want your drive pedals to be the whole story of your tone, this is the amp that gets out of the way - assuming you can carry it.',NULL,ARRAY['twin reverb','fender','twin','85 watts','clean','headroom','pedal platform','jazz','blackface']::text[],ARRAY['Johnny Marr','Ike Turner','James Burton']::text[],'{}',80,'Fender 65 Twin Reverb amp')

on conflict (id) do nothing;

-- Alternatives --------------------------------------------------------------

insert into public.alternatives
  (id, slug, original_id, name, brand, price_gbp, blurb,
   image_credit, pros, cons, aliases, popularity, match_quality, search_query, verdict)
values

-- Boss SD-1 -----------------------------------------------------------------
('alt-od300','behringer-od300-overdrive-distortion','org-sd-1','Behringer OD300 Overdrive/Distortion','Behringer',27,'Two gain stages in a plastic box, for less than a set of strings.',NULL,ARRAY['Covers mild overdrive and full distortion in one pedal','Costs roughly a fifth of the Boss it stands next to','Genuinely usable low-gain sounds once the tone control is set']::text[],ARRAY['Plastic enclosure and switch that will not survive heavy gigging','Noisier than the SD-1 with the gain up','The distortion side is fizzier and less controlled than the overdrive side']::text[],'{}',72,78,NULL,'Owners are consistent: it does not feel like a Boss, and at this price nobody expected it to. As a first overdrive or a spare, it is hard to argue with.'),

('alt-orange-burst','caline-orange-burst','org-sd-1','Caline Orange Burst','Caline',35,'A metal-boxed take on the classic mid-pushing overdrive.',NULL,ARRAY['Full metal enclosure and true bypass at a budget price','Holds together better than the plastic clones at higher gain','Stacks well in front of an already-driven amp']::text[],ARRAY['Voicing is brighter than the Boss it stands in for','Knobs sit close together and are awkward to adjust by foot','Quality control varies between units']::text[],'{}',68,82,NULL,'A common recommendation as the step up from the very cheapest clones - the metal box and true bypass are what people mention first.'),

-- MXR Dyna Comp -------------------------------------------------------------
('alt-ultimate-comp','donner-ultimate-comp','org-dyna-comp','Donner Ultimate Comp','Donner',39,'A two-knob squash pedal in a small metal enclosure.',NULL,ARRAY['Sustain and Level laid out the same way as the original','Small aluminium housing with true bypass','The squashed, popping character is genuinely present']::text[],ARRAY['Adds audible hiss with the sustain up','No attack control, so no way to soften the pop','Feels lighter and less solid than an MXR box']::text[],'{}',74,84,NULL,'Regularly named as the cheap way into this specific compression sound. The noise floor is the recurring complaint - as it is with the original.'),

('alt-jf10','joyo-jf-10-dynamic-compressor','org-dyna-comp','Joyo JF-10 Dynamic Compressor','Joyo',35,'The same idea in a metal box with true bypass.',NULL,ARRAY['Metal housing and true bypass for very little money','Compression character tracks the original closely','Quieter than the plastic budget compressors']::text[],ARRAY['Full-size enclosure takes as much board space as the pedal it replaces','Graphics wear off with use','Can pump audibly on hard strumming']::text[],'{}',74,84,NULL,'The sensible middle option: not the cheapest, but the one people tend to keep on the board rather than replace.'),

('alt-yellow-comp','mooer-yellow-comp','org-dyna-comp','Mooer Yellow Comp','Mooer',59,'An optical compressor in a micro box - smoother than the pedal beside it.',NULL,ARRAY['Optical circuit is noticeably quieter than the OTA budget clones','Micro enclosure frees up half the board space','Sounds more natural on chords and fingerpicking']::text[],ARRAY['Smoother and less squashed than a Dyna Comp - not the same effect','No battery option, 9V adapter only','The characteristic country pop is much less pronounced']::text[],'{}',82,72,NULL,'Well liked, but for a different reason than the Dyna Comp is. Players after transparent compression prefer it; players chasing the squash do not.'),

-- EHX Small Clone -----------------------------------------------------------
('alt-jf07','joyo-jf-07-classic-chorus','org-small-clone','Joyo JF-07 Classic Chorus','Joyo',35,'Analogue-voiced chorus in a metal box, aimed at the classic thick warble.',NULL,ARRAY['Warm, analogue-leaning voicing rather than a sterile digital one','Metal enclosure and true bypass','Subtle settings are usable, not just the extreme ones']::text[],ARRAY['Full-size box for a fairly simple effect','Depth at maximum gets seasick quickly','Some units run noisier than others']::text[],'{}',76,82,NULL,'A long-standing budget recommendation. Players who want one chorus and then never think about it again tend to end up here.'),

-- Boss TR-2 -----------------------------------------------------------------
('alt-golden-tremolo','donner-golden-tremolo','org-tr-2','Donner Golden Tremolo','Donner',32,'A compact analogue tremolo at the bottom of the price range.',NULL,ARRAY['Analogue circuit at a genuinely low price','Small aluminium enclosure and true bypass','Speed range goes usefully slow']::text[],ARRAY['Only Rate and Depth - no waveform control like the Boss','Volume drop is noticeable with the depth up','Build feels light next to a Boss enclosure']::text[],'{}',66,76,NULL,'Does the job for the money. Most owners describe it as fine rather than special, which at this price is the expected verdict.'),

-- Boss PH-3 -----------------------------------------------------------------
('alt-vp1','behringer-vp1-vintage-phaser','org-ph-3','Behringer VP1 Vintage Phaser','Behringer',29,'A one-knob phaser that goes straight for the classic sweep.',NULL,ARRAY['A single Rate control makes it very hard to get a bad sound out of','The classic four-stage sweep is present and correct','Costs a quarter of the Boss']::text[],ARRAY['Plastic enclosure','One control - none of the PH-3''s modes or tap tempo','Some hiss when engaged']::text[],'{}',66,70,NULL,'On the sweep alone it is good value. Against the PH-3''s feature list it is a different pedal entirely, which the price reflects.'),

-- DigiTech Whammy -----------------------------------------------------------
('alt-pitch-box','mooer-pitch-box','org-whammy','Mooer Pitch Box','Mooer',69,'Harmony, detune and pitch shifting in a micro box - without the treadle.',NULL,ARRAY['Three modes covering harmony, pitch shift and detune','A fraction of the price of the pedal it stands in for','Tracks single notes cleanly']::text[],ARRAY['No expression treadle, so no real-time sweeping - this is the big one','Chord tracking is poor, as with most budget pitch shifters','Fixed intervals only']::text[],'{}',78,64,NULL,'Good at fixed harmony work and detune. Nobody pretends it replaces the treadle - if the sweep is the sound you are after, this is not it.'),

-- EHX Deluxe Memory Man -----------------------------------------------------
('alt-blue-ocean','caline-blue-ocean-delay','org-memory-man','Caline Blue Ocean Delay','Caline',39,'Three delay modes in a metal box, with long repeats for the money.',NULL,ARRAY['Three modes covering short slapback through to long, washy repeats','Metal enclosure and true bypass at a low price','Repeat times go usefully longer than most budget analogue delays']::text[],ARRAY['Digital rather than bucket-brigade, so the repeats stay bright rather than darkening','No modulation on the tail, which is half of what a Memory Man is for','Mix control can swamp the dry signal at high settings']::text[],'{}',76,68,NULL,'Frequently recommended as a first delay for the price. It covers the timing side of the Memory Man and none of the analogue drift.'),

-- Strymon blueSky -----------------------------------------------------------
('alt-skysurfer','tc-electronic-skysurfer-reverb','org-bluesky','TC Electronic Skysurfer Reverb','TC Electronic',39,'Spring, hall and plate reverb from a company that knows how to do it.',NULL,ARRAY['Three genuinely distinct reverb types','From a major manufacturer rather than an unbranded clone','Clean, quiet and simple - three knobs and a switch']::text[],ARRAY['No shimmer or modulated modes, which are the blueSky''s signature','Fixed voicings with no deeper editing','Not true bypass']::text[],'{}',82,66,NULL,'Very well reviewed for the money as a straightforward reverb. It covers the blueSky''s bread and butter and none of its ambient tricks.'),

-- Fender '65 Deluxe Reverb --------------------------------------------------
('alt-katana-50','boss-katana-50-mkii','org-deluxe-reverb','Boss Katana 50 MkII','Boss',249,'50 modelling watts with five amp voicings and effects built in.',NULL,ARRAY['Clean voicing has real headroom and works well as a pedal platform','Built-in reverb, delay and modulation, editable from Tone Studio','0.5W power setting makes it usable at home']::text[],ARRAY['Modelling rather than valve - it does not bloom and compress the same way','Menu diving through the app to get the most out of it','Clean voicing is flatter and less scooped than blackface Fender clean']::text[],'{}',88,64,NULL,'The default budget recommendation for a loud, clean, pedal-friendly amp. The gap against a real Deluxe shows in the response rather than the volume.'),

-- Marshall JCM800 -----------------------------------------------------------
('alt-origin-20c','marshall-origin-20c','org-jcm800','Marshall Origin 20C','Marshall',499,'An actual Marshall valve combo, at a quarter of the price of the classic.',NULL,ARRAY['A genuine Marshall valve amp rather than an imitation of one','Powerstem attenuation takes 20W down to 3W and 0.5W','The Tilt control blends the two classic input voicings']::text[],ARRAY['Single channel with less gain on tap than a JCM800','20 watts through one speaker rather than a 100W head into a 4x12','Cleans break up earlier than some players expect']::text[],'{}',84,78,NULL,'The most direct route to Marshall crunch on a budget, and the one people recommend ahead of any clone. It runs out of gain where the 800 keeps going.'),

('alt-ht5r','blackstar-ht-5r-mkii','org-jcm800','Blackstar HT-5R MkII','Blackstar',479,'5 valve watts with reverb, an effects loop and a genuinely useful gain channel.',NULL,ARRAY['Two channels, so clean and drive without reaching for a pedal','ISF control sweeps the voicing between American and British','Digital reverb and a proper effects loop at this price']::text[],ARRAY['5 watts will not hold a stage against a drummer','Preamp gain is tighter and more modern than a JCM800''s','Small speaker limits the low end']::text[],'{}',80,70,NULL,'A long-standing pick for players who want valve feel and high gain at home. The ISF gets it into Marshall territory without ever quite being one.'),

-- Fender '65 Twin Reverb ----------------------------------------------------
('alt-katana-100','boss-katana-100-mkii','org-twin-reverb','Boss Katana 100 MkII','Boss',379,'100 modelling watts of clean headroom, with a pedal-platform voicing built in.',NULL,ARRAY['Enormous clean headroom - it will not break up before the room complains','Clean and acoustic voicings work well as a pedal platform','Built-in effects, Tone Studio editing and a 0.5W setting for home']::text[],ARRAY['Modelling rather than valve, so the clean does not bloom the same way','Heavy menu diving to get the most out of it','One 12" speaker rather than the Twin''s two']::text[],'{}',88,66,NULL,'The usual recommendation for a loud, clean, pedal-friendly amp on a budget. What it does not reproduce is how a valve Twin responds as you dig in.'),

('alt-spark-40','positive-grid-spark-40','org-twin-reverb','Positive Grid Spark 40','Positive Grid',239,'A 40-watt modelling combo aimed at practice, with app-driven amp models.',NULL,ARRAY['Large range of amp and effect models through the app','Smart jam and backing-track features for practising alone','Compact, and genuinely good sounding at low volume']::text[],ARRAY['Very much a practice amp - 40W of modelling will not hold a stage','Depends on the app for deeper editing','Small speaker with a limited low end']::text[],'{}',82,52,NULL,'Excellent at what it is built for, which is practising at home. It is here as the cheap end of the clean-amp ladder, not as a Twin replacement.')

on conflict (id) do nothing;
