-- ---------------------------------------------------------------------------
-- Amps, broken down by type.
--
-- Run this BEFORE 04 and 05 if you haven't run them yet, or after - either
-- order works, it only touches the CHECK constraint and existing rows.
--
-- "amp" as a single category was too coarse: a valve combo, a modelling box
-- and a speaker cab all landed in one list, implying they are alternatives to
-- one another. Three new categories, and the old `amp` is kept as a catch-all
-- so nothing 500s if a row is missed.
-- ---------------------------------------------------------------------------

-- 1. Widen the CHECK constraint ---------------------------------------------
-- Constraint names are generated by Postgres from the table and column, so
-- this drops by the conventional name. If yours differs, check with:
--   select conname from pg_constraint where conrelid = 'public.originals'::regclass;

alter table public.originals drop constraint if exists originals_category_check;

alter table public.originals add constraint originals_category_check
  check (category in (
    'overdrive','distortion','fuzz','delay','modulation','octave','eq','reverb',
    'amp','amp-valve','amp-modelling','amp-cab'
  ));

-- 2. Reclassify the amps already in the catalogue ---------------------------

update public.originals set category = 'amp-valve'
  where slug in (
    'fender-blues-junior',
    'marshall-dsl40',
    'vox-ac30',
    'orange-rocker-15',
    'fender-65-deluxe-reverb',
    'marshall-jcm800-2203',
    'fender-65-twin-reverb',
    'evh-5150iii-50w'
  );

-- The JC-40 is a solid-state amp; it is the one classic clean amp that is not
-- a valve design, and filing it under valve would be wrong.
update public.originals set category = 'amp-modelling'
  where slug in ('roland-jc-40');

-- 3. Anything still on the generic category, for review ---------------------
-- Run this after the updates above. Rows it returns show under "Other Amps"
-- until you file them.

-- select slug, name, brand from public.originals where category = 'amp';
